services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=./database.db
      - CLIENT_ID=114549057021-1regresnv2eue5ig42h76idmn34rh38s.apps.googleusercontent.com
      - SESSION_SECRET=TripsphereEdoCorti
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./API:/app
      #- /app/node_modules

  frontend:
    build:
      context: ./APP/tripsphere
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./APP/tripsphere:/app
      - /app/node_modules

